---
abstract: unknown
author:
  - 'GRNOC Software Engineering <globalnoc@iu.edu>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: grnoc-routerproxy
no_index:
  directory:
    - t
    - inc
requires: {}
version: v1.7.7
